### ISSUE TITLE
釣果とかランキングはスレッドに投稿するよう修正

### ISSUE THREAD

**Issue by shngmsw** [april-knights-dev/fishing-bot#5]
> 釣果とかランキングはスレッドに投稿するとかできないかな
<sub>[View in Slack](https://aprilknights.slack.com/archives/C014035DNQL/p1593670543156100)</sub>

_Originally posted by @shngmsw in https://github.com/april-knights-dev/fishing-bot/issues/2#issuecomment-652812198_

**Comment by kiddykazz** [comment]
エビデンス
ランキング：
![image](https://user-images.githubusercontent.com/67847947/88516916-038c8a00-d029-11ea-8d5c-77f3b6682676.png)
釣果：
![image](https://user-images.githubusercontent.com/67847947/88516982-1b640e00-d029-11ea-85bc-9349c9ffaf06.png)

こちらのイメージ通りになっているのでOKです！

**Comment by shngmsw** [comment]
本番環境で動作確認済み
