### ISSUE TITLE
車が釣れた時のコメントをボルクスワーゲンからフォルクスワーゲンに変える

### ISSUE THREAD

**Issue by kiddykazz** [april-knights-dev/fishing-bot#7]

**Comment by Khiroka** [comment]
エビデンス  
問題なければclose
こういうのって誰がcloseするのが正解なんですか

![Uploading スクリーンショット 2020-07-07 11.16.50.png…]()

**Comment by shngmsw** [comment]
んー、ペアでやってるから片方が確認してからクローズのほうが情報共有も兼ねていい気はしますね。
コードと紐付いてるissuesならプルリク確認してマージと同時にclose？

**Comment by kiddykazz** [comment]
>んー、ペアでやってるから片方が確認してからクローズのほうが情報共有も兼ねていい気はしますね。
>コードと紐付いてるissuesならプルリク確認してマージと同時にclose？

でいいかと。
修正者じゃないほうがクローズって感じにすれば一人で全部やるって感じにはならないかなって

**Comment by shngmsw** [comment]
OK
